name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag builder:latest
    - name: run image
      run: docker run --rm --name builder -v $(pwd)/build:/usr/src/builder/build builder:latest
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PharBuilder.phar
        path: build/PharBuilder.phar
    - name: Download builder
      uses: actions/download-artifact@v3
      with:
        name: compiler.phar
