name: Docker Image CI
on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gridorius/phnet
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: actions/checkout@v2
      - run: echo "PROJECT_JSON=$(jq -c . < ./src/Builder/PhnetBuilder.proj.json)" >> $GITHUB_ENV

      - name: extract deb package
        if: endsWith(github.event.ref, 'release')
        uses: shrink/actions-docker-extract@v3
        id: extract
        with:
          image: gridorius/phnet:latest
          path: /phnet.${{fromJson(env.PROJECT_JSON).version}}_all.deb

      - name: release
        if: endsWith(github.event.ref, 'release')
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: |
            Body
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload deb package
        if: endsWith(github.event.ref, 'release')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "${{ steps.extract.outputs.destination }}/phnet.${{fromJson(env.PROJECT_JSON).version}}_all.deb"
          asset_name: phnet.${{fromJson(env.PROJECT_JSON).version}}_all.deb
          asset_content_type: application/vnd.debian.binary-package
